WORLD_OBJECTS = [
    {
        "id": "tree_01",
        "name": "Árbol",
        "type": "tree",
        "x": 120,
        "y": 160,
        "radius": 24,
        "icon": "T",
        "hp": 3,
        "max_hp": 3,
        "required_tool": "axe",
        "energy_cost": 2,
        "reward_on_hit": {},
        "reward_on_destroy": {"wood": [4, 8]},
    },
    {
        "id": "tree_02",
        "name": "Árbol",
        "type": "tree",
        "x": 210,
        "y": 190,
        "radius": 24,
        "icon": "T",
        "hp": 3,
        "max_hp": 3,
        "required_tool": "axe",
        "energy_cost": 2,
        "reward_on_hit": {},
        "reward_on_destroy": {"wood": [4, 8]},
    },
    {
        "id": "tree_03",
        "name": "Árbol",
        "type": "tree",
        "x": 320,
        "y": 140,
        "radius": 24,
        "icon": "T",
        "hp": 3,
        "max_hp": 3,
        "required_tool": "axe",
        "energy_cost": 2,
        "reward_on_hit": {},
        "reward_on_destroy": {"wood": [4, 8]},
    },
    {
        "id": "rock_01",
        "name": "Roca",
        "type": "rock",
        "x": 440,
        "y": 260,
        "radius": 22,
        "icon": "R",
        "hp": 4,
        "max_hp": 4,
        "required_tool": "pickaxe",
        "energy_cost": 3,
        "reward_on_hit": {},
        "reward_on_destroy": {
            "iron": [2, 5],
            "carbon": [1, 3],
        },
    },
    {
        "id": "rock_02",
        "name": "Roca",
        "type": "rock",
        "x": 530,
        "y": 320,
        "radius": 22,
        "icon": "R",
        "hp": 4,
        "max_hp": 4,
        "required_tool": "pickaxe",
        "energy_cost": 3,
        "reward_on_hit": {},
        "reward_on_destroy": {
            "iron": [2, 5],
            "carbon": [1, 3],
        },
    },
    {
        "id": "bush_01",
        "name": "Arbusto",
        "type": "bush",
        "x": 250,
        "y": 360,
        "radius": 20,
        "icon": "B",
        "hp": 1,
        "max_hp": 1,
        "required_tool": None,
        "energy_cost": 1,
        "reward_on_hit": {},
        "reward_on_destroy": {"food": [2, 5]},
    },
    {
        "id": "bush_02",
        "name": "Arbusto",
        "type": "bush",
        "x": 350,
        "y": 410,
        "radius": 20,
        "icon": "B",
        "hp": 1,
        "max_hp": 1,
        "required_tool": None,
        "energy_cost": 1,
        "reward_on_hit": {},
        "reward_on_destroy": {"food": [2, 5]},
    },
    {
        "id": "fishing_spot_01",
        "name": "Zona de pesca",
        "type": "fishing_spot",
        "x": 700,
        "y": 420,
        "radius": 26,
        "icon": "F",
        "hp": 1,
        "max_hp": 1,
        "required_tool": "fishing_rod",
        "energy_cost": 3,
        "reward_on_hit": {},
        "reward_on_destroy": {"gold": [20, 60]},
    },
    {
        "id": "dock_01",
        "name": "Muelle",
        "type": "dock",
        "x": 740,
        "y": 170,
        "radius": 28,
        "icon": "D",
        "required_tool": None,
        "energy_cost": 0,
    },

    {
        "id": "bed_01",
        "name": "Cama",
        "type": "bed",
        "x": 120,
        "y": 520,
        "radius": 24,
        "icon": "B",
        "required_tool": None,
        "energy_cost": 0,
    },
]